version: '3.8'

services:
  alpino:
    image: registry.webhosting.rug.nl/compling/alpino:latest
    command: Alpino -notk -veryfast user_max=600000 server_kind=parse server_port=7001 assume_input_is_tokenized=on end_hook=xml -init_dict_p batch_command=alpino_server
    ports:
      - 7001:7001
  
  db:
    image: postgres
    environment:
      - POSTGRES_DB=sasta
      - POSTGRES_USER=sasta
      - POSTGRES_PASSWORD=sasta
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ./backend
    volumes:
      - type: bind
        source: ./backend
        target: /app
      - static_data:/app/staticfiles
    depends_on:
      - db
    env_file:
      - ./.env.dev
    command: python manage.py runserver 0.0.0.0:8000
  
  frontend:
    build:
      context: ./frontend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
    command: ng serve --host 0.0.0.0

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/static
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443

volumes:
  postgres_data:
  static_data: 