site_name: SASTA Documentatie
repo_url: https://github.com/UUDigitalHumanitieslab/sasta

theme:
    name: material
    language: nl
    logo: assets/uu.svg
    favicon: assets/favicon.svg

nav:
    - Home: 'index.md'
    - Gebruikersaccount: 'accounts.md'
    - Uploaden van transcripten: 'upload.md'
    - Voorbewerking (process): 'process.md'
    - Corpus-overzicht: 'corpora.md'
    - Transcript-overzicht: 'transcript.md'
    - Invoerformaten:
        - Anonimisatie: 'input-formats/anonimisatie.md'
        - SASTA Input Format (SIF): 'input-formats/sif.md'
        - Voorbeeldbestanden: 'input-formats/voorbeelden.md'
