# Generated by Django 3.2.25 on 2025-05-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_assessmentquery_literal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquery',
            name='variants',
        ),
    ]
