# Generated by Django 3.2.25 on 2025-05-28 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_remove_assessmentquery_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquery',
            name='variants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
