# Generated by Django 3.2.25 on 2026-03-27 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_assessmentquery_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='allresults',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='implies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
