# Generated by Django 3.2.25 on 2026-04-07 10:08

import analysis.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_assessmentquery_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='allresults',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='annotation_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=analysis.models.AnalysisRun.upload_path),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='query_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=analysis.models.AnalysisRun.upload_path),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='implies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
