# Generated by Django 3.2.25 on 2025-10-29 09:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_assessmentquery_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='share_permission',
            field=models.BooleanField(default=False, verbose_name='Permission to share data'),
        ),
        migrations.AlterField(
            model_name='assessmentquery',
            name='implies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, null=True, size=None),
        ),
    ]
