# Generated by Django 3.2.25 on 2025-10-29 14:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0036_auto_20251029_1000'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corpus',
            unique_together={('user', 'name')},
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='status',
        ),
    ]
