# Generated by Django 3.2.25 on 2026-04-07 20:02

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_async_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='annotated_chat_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=analysis.models.AnalysisRun.upload_path),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='form_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=analysis.models.AnalysisRun.upload_path),
        ),
    ]
